# Generated by agents/build_asi_hosted.py. Edit the tested source modules.
"""ACP transport for the native mutuals Pre/Post backend; no business data lives here."""
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from uuid import uuid4

from uagents import Context, Protocol
from uagents_core.contrib.protocols.chat import (
    ChatAcknowledgement, ChatMessage, EndSessionContent, TextContent, chat_protocol_spec,
)


def session_key(address: str, sender: str, session: str) -> str:
    return hashlib.sha256(json.dumps([address, sender, session]).encode()).hexdigest()


def request_key(session: str, message_id: str) -> str:
    return 'asi_' + hashlib.sha256(json.dumps([session, message_id]).encode()).hexdigest()


def make_protocol(address: str, backend) -> Protocol:
    protocol = Protocol(spec=chat_protocol_spec)

    @protocol.on_message(ChatMessage)
    async def handle_message(ctx: Context, sender: str, msg: ChatMessage):
        await ctx.send(sender, ChatAcknowledgement(timestamp=datetime.now(timezone.utc), acknowledged_msg_id=msg.msg_id))
        text = ''.join(item.text for item in msg.content if isinstance(item, TextContent)).strip()
        ended = any(isinstance(item, EndSessionContent) for item in msg.content)
        session = getattr(ctx, 'session', None)
        reply = 'Welcome to mutuals. I help with event preparation and follow-up. Link your website account with link <code>.'
        if not session:
            reply = 'A verified chat session is required. Please start a new ASI:One session.'
        elif text or ended:
            key = session_key(address, sender, str(session))
            # Metadata only: never log the message, binding code or private reply.
            ctx.logger.info(f'ACP session={key} request={request_key(key, str(msg.msg_id))}')
            try:
                result = await backend({'sessionKey': key, 'requestId': request_key(key, str(msg.msg_id)),
                                        'message': 'unlink' if ended else text})
                reply = result['reply']
            except Exception:
                reply = 'The mutuals service could not complete this request. Please retry.'
        content = [TextContent(type='text', text=reply)]
        if ended:
            content.append(EndSessionContent(type='end-session'))
        await ctx.send(sender, ChatMessage(timestamp=datetime.now(timezone.utc), msg_id=uuid4(), content=content))

    @protocol.on_message(ChatAcknowledgement)
    async def handle_ack(ctx: Context, sender: str, msg: ChatAcknowledgement):
        pass

    return protocol



"""Hosted transport adapter; all account permissions and business logic stay native."""
import json
import re


class NativeChatBackend:
    def __init__(self, rpc):
        self.rpc = rpc

    async def __call__(self, payload):
        key, request, message = payload['sessionKey'], payload['requestId'], payload['message'].strip()
        if message.lower() == 'unlink':
            await self.rpc('unlink_asi_chat', [key])
            return {'reply': 'This chat is disconnected from your mutuals account.'}
        if re.match(r'^link\s+', message, re.I):
            code = re.sub(r'^link\s+', '', message, flags=re.I).strip()
            if not re.fullmatch(r'[a-f0-9]{32}', code):
                return {'reply': 'Use link <code> with the five-minute code from your website account.'}
            try:
                await self.rpc('redeem_asi_link_code', [code, key, request])
                return {'reply': 'Your mutuals account is linked to this chat for up to 24 hours. Send events to choose an event; send unlink to disconnect.'}
            except RuntimeError as e:
                if re.search(r'code|profile|switching accounts', str(e), re.I):
                    return {'reply': 'The code could not be redeemed. Save your website profile and generate a new code; unlink first to switch accounts.'}
                raise
        try:
            context = json.loads(await self.rpc('get_asi_chat_context', [key]))
        except RuntimeError as e:
            if re.search(r'authorization|link.*again|website profile', str(e), re.I):
                return {'reply': 'Link your account first: sign in at https://mutuals.tech/events, generate a code, then send link <code>. Pre and Post work here; During uses website GPS.'}
            raise
        events = context['events']
        choices = '\n'.join(f"{e['title']} ({e['phase']}) — event {e['event_id']}" for e in events)
        if message.lower() == 'events':
            return {'reply': choices or 'You have not joined an event on the mutuals website yet.'}
        if re.match(r'^event\s+', message, re.I):
            event_id = re.sub(r'^event\s+', '', message, flags=re.I).strip()
            selected = next((e for e in events if e['event_id'] == event_id), None)
            if not selected:
                return {'reply': 'That event is unavailable to your account.\n' + choices}
            await self.rpc('select_asi_event', [key, event_id])
            return {'reply': f"Selected {selected['title']} ({selected['phase']}). Ask your Pre/Post assistant a question. In Post, send recap."}
        selected = next((e for e in events if e['event_id'] == context['selected_event_id']), None)
        if not selected and len(events) == 1:
            selected = events[0]
        if not selected:
            return {'reply': 'Select an event by sending its event command:\n' + choices if events else 'Join an event on the mutuals website first.'}
        if message.lower() in ('recap', '回顾', '总结活动') and selected['phase'] == 'post':
            return json.loads(await self.rpc('generate_asi_event_recap', [key, selected['event_id'], request]))
        return json.loads(await self.rpc('send_asi_assistant_message', [key, selected['event_id'], message, request]))

"""Hosted entry point; build_asi_hosted.py creates the uploadable single-file artifact."""
import os
import httpx


async def native_rpc(name, args):
    token = os.environ.get('ASI_CHAT_SERVICE_TOKEN', '')
    if not token:
        raise RuntimeError('The dedicated service secret is not configured.')
    url = 'https://maincloud.spacetimedb.com/v1/database/mhacks-live-map/call/' + name
    async with httpx.AsyncClient(timeout=180) as client:
        response = await client.post(url, json=args, headers={'Authorization': 'Bearer ' + token})
    if not response.is_success:
        # Read native authorization errors, but never log raw responses/credentials.
        raise RuntimeError(response.text)
    return response.json() if response.content else None


async def backend(payload):
    if os.environ.get('ASI_CHAT_ENABLED', 'false').lower() != 'true':
        return {'reply': 'mutuals Hosted ACP is online. Private account access is not enabled yet. I support Pre and Post; During uses website GPS.'}
    return await NativeChatBackend(native_rpc)(payload)


# Agentverse provides this instance and its identity. Do not create a local Agent,
# run a listener, load .env, or copy a website/administrator token into this file.
agent.include(make_protocol(agent.address, backend), publish_manifest=True)  # noqa: F821
