// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ApproveCloudFollowupReducer from "../approve_cloud_followup_reducer";
import CreateAgentLinkCodeReducer from "../create_agent_link_code_reducer";
import DeleteAgentPresenceReducer from "../delete_agent_presence_reducer";
import DeleteAgentRecordReducer from "../delete_agent_record_reducer";
import DeleteMyAgentDataReducer from "../delete_my_agent_data_reducer";
import LeaveCloudEventReducer from "../leave_cloud_event_reducer";
import LeaveMapReducer from "../leave_map_reducer";
import LinkAgentUserReducer from "../link_agent_user_reducer";
import PutAgentEventReducer from "../put_agent_event_reducer";
import PutAgentFollowUpPlanReducer from "../put_agent_follow_up_plan_reducer";
import PutAgentInteractionReducer from "../put_agent_interaction_reducer";
import PutAgentPresenceReducer from "../put_agent_presence_reducer";
import PutAgentProfileReducer from "../put_agent_profile_reducer";
import PutAgentRoiHistoryReducer from "../put_agent_roi_history_reducer";
import PutAgentTranscriptReducer from "../put_agent_transcript_reducer";
import RecordCloudOutcomeReducer from "../record_cloud_outcome_reducer";
import RedeemAgentLinkCodeReducer from "../redeem_agent_link_code_reducer";
import RequestCloudConnectionReducer from "../request_cloud_connection_reducer";
import RespondCloudConnectionReducer from "../respond_cloud_connection_reducer";
import SaveMyProfileReducer from "../save_my_profile_reducer";
import SetCloudPreferencesReducer from "../set_cloud_preferences_reducer";
import SetCloudPresenceReducer from "../set_cloud_presence_reducer";
import SetMyPresenceReducer from "../set_my_presence_reducer";
import StopSharingLocationReducer from "../stop_sharing_location_reducer";
import UpdateMyLocationReducer from "../update_my_location_reducer";

export type ApproveCloudFollowupParams = __Infer<typeof ApproveCloudFollowupReducer>;
export type CreateAgentLinkCodeParams = __Infer<typeof CreateAgentLinkCodeReducer>;
export type DeleteAgentPresenceParams = __Infer<typeof DeleteAgentPresenceReducer>;
export type DeleteAgentRecordParams = __Infer<typeof DeleteAgentRecordReducer>;
export type DeleteMyAgentDataParams = __Infer<typeof DeleteMyAgentDataReducer>;
export type LeaveCloudEventParams = __Infer<typeof LeaveCloudEventReducer>;
export type LeaveMapParams = __Infer<typeof LeaveMapReducer>;
export type LinkAgentUserParams = __Infer<typeof LinkAgentUserReducer>;
export type PutAgentEventParams = __Infer<typeof PutAgentEventReducer>;
export type PutAgentFollowUpPlanParams = __Infer<typeof PutAgentFollowUpPlanReducer>;
export type PutAgentInteractionParams = __Infer<typeof PutAgentInteractionReducer>;
export type PutAgentPresenceParams = __Infer<typeof PutAgentPresenceReducer>;
export type PutAgentProfileParams = __Infer<typeof PutAgentProfileReducer>;
export type PutAgentRoiHistoryParams = __Infer<typeof PutAgentRoiHistoryReducer>;
export type PutAgentTranscriptParams = __Infer<typeof PutAgentTranscriptReducer>;
export type RecordCloudOutcomeParams = __Infer<typeof RecordCloudOutcomeReducer>;
export type RedeemAgentLinkCodeParams = __Infer<typeof RedeemAgentLinkCodeReducer>;
export type RequestCloudConnectionParams = __Infer<typeof RequestCloudConnectionReducer>;
export type RespondCloudConnectionParams = __Infer<typeof RespondCloudConnectionReducer>;
export type SaveMyProfileParams = __Infer<typeof SaveMyProfileReducer>;
export type SetCloudPreferencesParams = __Infer<typeof SetCloudPreferencesReducer>;
export type SetCloudPresenceParams = __Infer<typeof SetCloudPresenceReducer>;
export type SetMyPresenceParams = __Infer<typeof SetMyPresenceReducer>;
export type StopSharingLocationParams = __Infer<typeof StopSharingLocationReducer>;
export type UpdateMyLocationParams = __Infer<typeof UpdateMyLocationReducer>;

