// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import LeaveMapReducer from "../leave_map_reducer";
import SetMyPresenceReducer from "../set_my_presence_reducer";

export type LeaveMapParams = __Infer<typeof LeaveMapReducer>;
export type SetMyPresenceParams = __Infer<typeof SetMyPresenceReducer>;

