// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  userId: __t.string().primaryKey().name("user_id"),
  zoneId: __t.string().name("zone_id"),
  availabilityStatus: __t.string().name("availability_status"),
  discoverable: __t.bool(),
  updatedAt: __t.timestamp().name("updated_at"),
  payloadJson: __t.string().name("payload_json"),
  agentScope: __t.string().name("agent_scope"),
});
