// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.string().primaryKey().name("event_id"),
  startAtMs: __t.u64().name("start_at_ms"),
  endAtMs: __t.u64().name("end_at_ms"),
  zoneId: __t.option(__t.string()).name("zone_id"),
  payloadJson: __t.string().name("payload_json"),
  agentScope: __t.string().name("agent_scope"),
});
