// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  interactionId: __t.string().primaryKey().name("interaction_id"),
  userId: __t.string().name("user_id"),
  targetId: __t.string().name("target_id"),
  text: __t.string(),
  audioRef: __t.option(__t.string()).name("audio_ref"),
  payloadJson: __t.string().name("payload_json"),
  agentScope: __t.string().name("agent_scope"),
});
