// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  interactionId: __t.string().primaryKey().name("interaction_id"),
  userId: __t.string().name("user_id"),
  targetId: __t.string().name("target_id"),
  status: __t.string(),
  roiScoreAtMatch: __t.f64().name("roi_score_at_match"),
  reason: __t.string(),
  recordingConsentJson: __t.string().name("recording_consent_json"),
  recordingActive: __t.bool().name("recording_active"),
  audioRef: __t.option(__t.string()).name("audio_ref"),
  transcriptRef: __t.option(__t.string()).name("transcript_ref"),
  createdAt: __t.timestamp().name("created_at"),
  payloadJson: __t.string().name("payload_json"),
  agentScope: __t.string().name("agent_scope"),
});
