// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  planId: __t.string().primaryKey().name("plan_id"),
  interactionId: __t.string().name("interaction_id"),
  userA: __t.string().name("user_a"),
  userB: __t.string().name("user_b"),
  payloadJson: __t.string().name("payload_json"),
  agentScope: __t.string().name("agent_scope"),
});
