/* Minimal typed client bindings. Run `npm run stdb:generate` after publishing
   to replace these with the bindings generated by the installed SpacetimeDB CLI. */
import {
  DbConnectionBuilder as BaseConnectionBuilder,
  DbConnectionImpl as BaseConnection,
  SubscriptionBuilderImpl as BaseSubscriptionBuilder,
  convertToAccessorMap,
  reducerSchema,
  reducers as buildReducers,
  schema as buildTableSchema,
  table,
  t,
  type DbConnectionConfig,
  type ErrorContextInterface,
  type EventContextInterface,
  type QueryBuilder,
  type ReducerEventContextInterface,
  type RemoteModule,
  type SubscriptionEventContextInterface,
  type SubscriptionHandleImpl,
} from 'spacetimedb/sdk';
import { makeQueryBuilder } from 'spacetimedb';

const tablesSchema = buildTableSchema({
  presence: table(
    { name: 'presence', public: true },
    {
      participantId: t.string().primaryKey(),
      zoneId: t.string().index('btree'),
      isDemoPersona: t.bool(),
    },
  ),
});

const reducersSchema = buildReducers(
  reducerSchema('set_my_presence', { participantId: t.string(), zoneId: t.string() }),
  reducerSchema('leave_map', { participantId: t.string() }),
);

const REMOTE_MODULE = {
  versionInfo: { cliVersion: '2.0.0' as const },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  procedures: [],
} satisfies RemoteModule<typeof tablesSchema.schemaType, typeof reducersSchema.reducersType, { procedures: readonly [] }>;

export const tables: QueryBuilder<typeof tablesSchema.schemaType> = makeQueryBuilder(tablesSchema.schemaType);
export const reducers = convertToAccessorMap(reducersSchema.reducersType.reducers);

export type EventContext = EventContextInterface<typeof REMOTE_MODULE>;
export type ReducerEventContext = ReducerEventContextInterface<typeof REMOTE_MODULE>;
export type SubscriptionEventContext = SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
export type ErrorContext = ErrorContextInterface<typeof REMOTE_MODULE>;
export type SubscriptionHandle = SubscriptionHandleImpl<typeof REMOTE_MODULE>;

export class SubscriptionBuilder extends BaseSubscriptionBuilder<typeof REMOTE_MODULE> {}
export class DbConnectionBuilder extends BaseConnectionBuilder<DbConnection> {}

export class DbConnection extends BaseConnection<typeof REMOTE_MODULE> {
  static builder = (): DbConnectionBuilder => new DbConnectionBuilder(
    REMOTE_MODULE,
    (config: DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config),
  );

  override subscriptionBuilder = (): SubscriptionBuilder => new SubscriptionBuilder(this);
}
