// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import ApproveCloudFollowupReducer from "./approve_cloud_followup_reducer";
import CreateAgentLinkCodeReducer from "./create_agent_link_code_reducer";
import DeleteAgentPresenceReducer from "./delete_agent_presence_reducer";
import DeleteAgentRecordReducer from "./delete_agent_record_reducer";
import DeleteMyAgentDataReducer from "./delete_my_agent_data_reducer";
import EditNetworkingEventReducer from "./edit_networking_event_reducer";
import FinishEventConnectionReducer from "./finish_event_connection_reducer";
import JoinNetworkingEventReducer from "./join_networking_event_reducer";
import LeaveCloudEventReducer from "./leave_cloud_event_reducer";
import LeaveMapReducer from "./leave_map_reducer";
import LeaveNetworkingEventReducer from "./leave_networking_event_reducer";
import LinkAgentUserReducer from "./link_agent_user_reducer";
import MarkAssistantNotificationReadReducer from "./mark_assistant_notification_read_reducer";
import PutAgentEventReducer from "./put_agent_event_reducer";
import PutAgentFollowUpPlanReducer from "./put_agent_follow_up_plan_reducer";
import PutAgentInteractionReducer from "./put_agent_interaction_reducer";
import PutAgentPresenceReducer from "./put_agent_presence_reducer";
import PutAgentProfileReducer from "./put_agent_profile_reducer";
import PutAgentRoiHistoryReducer from "./put_agent_roi_history_reducer";
import PutAgentTranscriptReducer from "./put_agent_transcript_reducer";
import RecordCloudOutcomeReducer from "./record_cloud_outcome_reducer";
import RedeemAgentLinkCodeReducer from "./redeem_agent_link_code_reducer";
import RequestCloudConnectionReducer from "./request_cloud_connection_reducer";
import RequestEventConnectionReducer from "./request_event_connection_reducer";
import RespondCloudConnectionReducer from "./respond_cloud_connection_reducer";
import RespondEventConnectionReducer from "./respond_event_connection_reducer";
import SaveMyProfileReducer from "./save_my_profile_reducer";
import SetCloudPreferencesReducer from "./set_cloud_preferences_reducer";
import SetCloudPresenceReducer from "./set_cloud_presence_reducer";
import SetEventAvailabilityReducer from "./set_event_availability_reducer";
import SetEventStarReducer from "./set_event_star_reducer";
import SetMyPresenceReducer from "./set_my_presence_reducer";
import SetNetworkingEventAreaReducer from "./set_networking_event_area_reducer";
import SetNetworkingEventPhaseReducer from "./set_networking_event_phase_reducer";
import StartNetworkingEventReducer from "./start_networking_event_reducer";
import StopEventLocationReducer from "./stop_event_location_reducer";
import StopSharingLocationReducer from "./stop_sharing_location_reducer";
import UpdateEventLocationReducer from "./update_event_location_reducer";
import UpdateMyLocationReducer from "./update_my_location_reducer";

// Import all procedure arg schemas
import * as CloudBackendStatusProcedure from "./cloud_backend_status_procedure";
import * as CreateNetworkingEventProcedure from "./create_networking_event_procedure";
import * as DeleteCloudAccountProcedure from "./delete_cloud_account_procedure";
import * as DeleteNetworkingEventProcedure from "./delete_networking_event_procedure";
import * as DraftCloudFollowupProcedure from "./draft_cloud_followup_procedure";
import * as GetCloudEventRecommendationsProcedure from "./get_cloud_event_recommendations_procedure";
import * as GetCloudOpportunitiesProcedure from "./get_cloud_opportunities_procedure";
import * as GetEventInterestListProcedure from "./get_event_interest_list_procedure";
import * as LoadCloudProfileProcedure from "./load_cloud_profile_procedure";
import * as NetworkingAccountStatusProcedure from "./networking_account_status_procedure";
import * as PrepareNetworkingEventProcedure from "./prepare_networking_event_procedure";
import * as SaveCloudEventProcedure from "./save_cloud_event_procedure";
import * as SendAssistantMessageProcedure from "./send_assistant_message_procedure";
import * as SubmitCloudIntroductionProcedure from "./submit_cloud_introduction_procedure";
import * as VerifyCloudProvidersProcedure from "./verify_cloud_providers_procedure";

// Import all table schema definitions
import AgentEventsRow from "./agent_events_table";
import AgentFollowUpPlansRow from "./agent_follow_up_plans_table";
import AgentInteractionsRow from "./agent_interactions_table";
import AgentLinkCodesRow from "./agent_link_codes_table";
import AgentPresencesRow from "./agent_presences_table";
import AgentProfilesRow from "./agent_profiles_table";
import AgentRoiHistoryRow from "./agent_roi_history_table";
import AgentTranscriptsRow from "./agent_transcripts_table";
import AgentUserLinksRow from "./agent_user_links_table";
import LiveLocationRow from "./live_location_table";
import MyAgentFollowUpPlansRow from "./my_agent_follow_up_plans_table";
import MyAgentInteractionsRow from "./my_agent_interactions_table";
import MyAgentRoiHistoryRow from "./my_agent_roi_history_table";
import MyAgentTranscriptsRow from "./my_agent_transcripts_table";
import MyAssistantMessagesRow from "./my_assistant_messages_table";
import MyAssistantNotificationsRow from "./my_assistant_notifications_table";
import MyEventMapPinsRow from "./my_event_map_pins_table";
import MyEventStarsRow from "./my_event_stars_table";
import MyNetworkingMembershipsRow from "./my_networking_memberships_table";
import MyProfileRow from "./my_profile_table";
import MyProfileDetailsRow from "./my_profile_details_table";
import NetworkingEventAreasRow from "./networking_event_areas_table";
import NetworkingInvitationsRow from "./networking_invitations_table";
import PresenceRow from "./presence_table";
import PublicProfilesRow from "./public_profiles_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  liveLocation: __table({
    name: 'live_location',
    indexes: [
      { accessor: 'participantId', name: 'live_location_participant_id_idx_btree', algorithm: 'btree', columns: [
        'participantId',
      ] },
    ],
    constraints: [
      { name: 'live_location_participant_id_key', constraint: 'unique', columns: ['participantId'] },
    ],
  }, LiveLocationRow),
  presence: __table({
    name: 'presence',
    indexes: [
      { accessor: 'participantId', name: 'presence_participant_id_idx_btree', algorithm: 'btree', columns: [
        'participantId',
      ] },
      { accessor: 'zoneId', name: 'presence_zone_id_idx_btree', algorithm: 'btree', columns: [
        'zoneId',
      ] },
    ],
    constraints: [
      { name: 'presence_participant_id_key', constraint: 'unique', columns: ['participantId'] },
    ],
  }, PresenceRow),
  agentEvents: __table({
    name: 'agent_events',
    indexes: [
    ],
    constraints: [
    ],
  }, AgentEventsRow),
  agentFollowUpPlans: __table({
    name: 'agent_follow_up_plans',
    indexes: [
    ],
    constraints: [
    ],
  }, AgentFollowUpPlansRow),
  agentInteractions: __table({
    name: 'agent_interactions',
    indexes: [
    ],
    constraints: [
    ],
  }, AgentInteractionsRow),
  agentLinkCodes: __table({
    name: 'agent_link_codes',
    indexes: [
    ],
    constraints: [
    ],
  }, AgentLinkCodesRow),
  agentPresences: __table({
    name: 'agent_presences',
    indexes: [
    ],
    constraints: [
    ],
  }, AgentPresencesRow),
  agentProfiles: __table({
    name: 'agent_profiles',
    indexes: [
    ],
    constraints: [
    ],
  }, AgentProfilesRow),
  agentRoiHistory: __table({
    name: 'agent_roi_history',
    indexes: [
    ],
    constraints: [
    ],
  }, AgentRoiHistoryRow),
  agentTranscripts: __table({
    name: 'agent_transcripts',
    indexes: [
    ],
    constraints: [
    ],
  }, AgentTranscriptsRow),
  agentUserLinks: __table({
    name: 'agent_user_links',
    indexes: [
    ],
    constraints: [
    ],
  }, AgentUserLinksRow),
  myAgentFollowUpPlans: __table({
    name: 'my_agent_follow_up_plans',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAgentFollowUpPlansRow),
  myAgentInteractions: __table({
    name: 'my_agent_interactions',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAgentInteractionsRow),
  myAgentRoiHistory: __table({
    name: 'my_agent_roi_history',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAgentRoiHistoryRow),
  myAgentTranscripts: __table({
    name: 'my_agent_transcripts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAgentTranscriptsRow),
  myAssistantMessages: __table({
    name: 'my_assistant_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAssistantMessagesRow),
  myAssistantNotifications: __table({
    name: 'my_assistant_notifications',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAssistantNotificationsRow),
  myEventMapPins: __table({
    name: 'my_event_map_pins',
    indexes: [
    ],
    constraints: [
    ],
  }, MyEventMapPinsRow),
  myEventStars: __table({
    name: 'my_event_stars',
    indexes: [
    ],
    constraints: [
    ],
  }, MyEventStarsRow),
  myNetworkingMemberships: __table({
    name: 'my_networking_memberships',
    indexes: [
    ],
    constraints: [
    ],
  }, MyNetworkingMembershipsRow),
  myProfile: __table({
    name: 'my_profile',
    indexes: [
    ],
    constraints: [
    ],
  }, MyProfileRow),
  myProfileDetails: __table({
    name: 'my_profile_details',
    indexes: [
    ],
    constraints: [
    ],
  }, MyProfileDetailsRow),
  networkingEventAreas: __table({
    name: 'networking_event_areas',
    indexes: [
    ],
    constraints: [
    ],
  }, NetworkingEventAreasRow),
  networkingInvitations: __table({
    name: 'networking_invitations',
    indexes: [
    ],
    constraints: [
    ],
  }, NetworkingInvitationsRow),
  publicProfiles: __table({
    name: 'public_profiles',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicProfilesRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("approve_cloud_followup", ApproveCloudFollowupReducer),
  __reducerSchema("create_agent_link_code", CreateAgentLinkCodeReducer),
  __reducerSchema("delete_agent_presence", DeleteAgentPresenceReducer),
  __reducerSchema("delete_agent_record", DeleteAgentRecordReducer),
  __reducerSchema("delete_my_agent_data", DeleteMyAgentDataReducer),
  __reducerSchema("edit_networking_event", EditNetworkingEventReducer),
  __reducerSchema("finish_event_connection", FinishEventConnectionReducer),
  __reducerSchema("join_networking_event", JoinNetworkingEventReducer),
  __reducerSchema("leave_cloud_event", LeaveCloudEventReducer),
  __reducerSchema("leave_map", LeaveMapReducer),
  __reducerSchema("leave_networking_event", LeaveNetworkingEventReducer),
  __reducerSchema("link_agent_user", LinkAgentUserReducer),
  __reducerSchema("mark_assistant_notification_read", MarkAssistantNotificationReadReducer),
  __reducerSchema("put_agent_event", PutAgentEventReducer),
  __reducerSchema("put_agent_follow_up_plan", PutAgentFollowUpPlanReducer),
  __reducerSchema("put_agent_interaction", PutAgentInteractionReducer),
  __reducerSchema("put_agent_presence", PutAgentPresenceReducer),
  __reducerSchema("put_agent_profile", PutAgentProfileReducer),
  __reducerSchema("put_agent_roi_history", PutAgentRoiHistoryReducer),
  __reducerSchema("put_agent_transcript", PutAgentTranscriptReducer),
  __reducerSchema("record_cloud_outcome", RecordCloudOutcomeReducer),
  __reducerSchema("redeem_agent_link_code", RedeemAgentLinkCodeReducer),
  __reducerSchema("request_cloud_connection", RequestCloudConnectionReducer),
  __reducerSchema("request_event_connection", RequestEventConnectionReducer),
  __reducerSchema("respond_cloud_connection", RespondCloudConnectionReducer),
  __reducerSchema("respond_event_connection", RespondEventConnectionReducer),
  __reducerSchema("save_my_profile", SaveMyProfileReducer),
  __reducerSchema("set_cloud_preferences", SetCloudPreferencesReducer),
  __reducerSchema("set_cloud_presence", SetCloudPresenceReducer),
  __reducerSchema("set_event_availability", SetEventAvailabilityReducer),
  __reducerSchema("set_event_star", SetEventStarReducer),
  __reducerSchema("set_my_presence", SetMyPresenceReducer),
  __reducerSchema("set_networking_event_area", SetNetworkingEventAreaReducer),
  __reducerSchema("set_networking_event_phase", SetNetworkingEventPhaseReducer),
  __reducerSchema("start_networking_event", StartNetworkingEventReducer),
  __reducerSchema("stop_event_location", StopEventLocationReducer),
  __reducerSchema("stop_sharing_location", StopSharingLocationReducer),
  __reducerSchema("update_event_location", UpdateEventLocationReducer),
  __reducerSchema("update_my_location", UpdateMyLocationReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("cloud_backend_status", CloudBackendStatusProcedure.params, CloudBackendStatusProcedure.returnType),
  __procedureSchema("create_networking_event", CreateNetworkingEventProcedure.params, CreateNetworkingEventProcedure.returnType),
  __procedureSchema("delete_cloud_account", DeleteCloudAccountProcedure.params, DeleteCloudAccountProcedure.returnType),
  __procedureSchema("delete_networking_event", DeleteNetworkingEventProcedure.params, DeleteNetworkingEventProcedure.returnType),
  __procedureSchema("draft_cloud_followup", DraftCloudFollowupProcedure.params, DraftCloudFollowupProcedure.returnType),
  __procedureSchema("get_cloud_event_recommendations", GetCloudEventRecommendationsProcedure.params, GetCloudEventRecommendationsProcedure.returnType),
  __procedureSchema("get_cloud_opportunities", GetCloudOpportunitiesProcedure.params, GetCloudOpportunitiesProcedure.returnType),
  __procedureSchema("get_event_interest_list", GetEventInterestListProcedure.params, GetEventInterestListProcedure.returnType),
  __procedureSchema("load_cloud_profile", LoadCloudProfileProcedure.params, LoadCloudProfileProcedure.returnType),
  __procedureSchema("networking_account_status", NetworkingAccountStatusProcedure.params, NetworkingAccountStatusProcedure.returnType),
  __procedureSchema("prepare_networking_event", PrepareNetworkingEventProcedure.params, PrepareNetworkingEventProcedure.returnType),
  __procedureSchema("save_cloud_event", SaveCloudEventProcedure.params, SaveCloudEventProcedure.returnType),
  __procedureSchema("send_assistant_message", SendAssistantMessageProcedure.params, SendAssistantMessageProcedure.returnType),
  __procedureSchema("submit_cloud_introduction", SubmitCloudIntroductionProcedure.params, SubmitCloudIntroductionProcedure.returnType),
  __procedureSchema("verify_cloud_providers", VerifyCloudProvidersProcedure.params, VerifyCloudProvidersProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

