// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  participantId: __t.string().primaryKey().name("participant_id"),
  latitude: __t.f64(),
  longitude: __t.f64(),
  accuracyMeters: __t.f64().name("accuracy_meters"),
  updatedAt: __t.timestamp().name("updated_at"),
});
