// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  exchangeId: __t.string().primaryKey().name("exchange_id"),
  userId: __t.string().name("user_id"),
  eventId: __t.string().name("event_id"),
  fromAgent: __t.string().name("from_agent"),
  toAgent: __t.string().name("to_agent"),
  question: __t.string(),
  response: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
