// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  planId: __t.string().name("plan_id"),
  interactionId: __t.string().name("interaction_id"),
  peerId: __t.string().name("peer_id"),
  channelsJson: __t.string().name("channels_json"),
  agreed: __t.bool(),
  yourDraft: __t.string().name("your_draft"),
  suggestedTiming: __t.string().name("suggested_timing"),
  rationale: __t.string(),
  approved: __t.bool(),
  sendStatus: __t.option(__t.string()).name("send_status"),
});
