// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  notificationId: __t.string().primaryKey().name("notification_id"),
  userId: __t.string().name("user_id"),
  eventId: __t.string().name("event_id"),
  stage: __t.string(),
  kind: __t.string(),
  targetId: __t.string().name("target_id"),
  interactionId: __t.string().name("interaction_id"),
  title: __t.string(),
  body: __t.string(),
  read: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
});
