// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  locationId: __t.string().primaryKey().name("location_id"),
  eventId: __t.string().name("event_id"),
  userId: __t.string().name("user_id"),
  name: __t.string(),
  headline: __t.string(),
  zoneId: __t.string().name("zone_id"),
  latitude: __t.f64(),
  longitude: __t.f64(),
  accuracyMeters: __t.f64().name("accuracy_meters"),
  updatedAt: __t.timestamp().name("updated_at"),
});
