// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  displayName: __t.string().name("display_name"),
  headline: __t.string(),
  interests: __t.string(),
  showOnMap: __t.bool().name("show_on_map"),
  updatedAt: __t.timestamp().name("updated_at"),
  agentProfileJson: __t.option(__t.string()).name("agent_profile_json"),
});
