// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  interactionId: __t.string(),
  userId: __t.string(),
  targetId: __t.string(),
  status: __t.string(),
  roiScoreAtMatch: __t.f64(),
  reason: __t.string(),
  recordingConsentJson: __t.string(),
  recordingActive: __t.bool(),
  audioRef: __t.option(__t.string()),
  transcriptRef: __t.option(__t.string()),
  payloadJson: __t.string(),
};
