// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ParticipantOwner = __t.object("ParticipantOwner", {
  participantId: __t.string(),
  ownerIdentity: __t.identity(),
});
export type ParticipantOwner = __Infer<typeof ParticipantOwner>;

export const Presence = __t.object("Presence", {
  participantId: __t.string(),
  zoneId: __t.string(),
  isDemoPersona: __t.bool(),
});
export type Presence = __Infer<typeof Presence>;

