// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const LiveLocation = __t.object("LiveLocation", {
  participantId: __t.string(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  accuracyMeters: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type LiveLocation = __Infer<typeof LiveLocation>;

export const MyProfile = __t.object("MyProfile", {});
export type MyProfile = __Infer<typeof MyProfile>;

export const ParticipantOwner = __t.object("ParticipantOwner", {
  participantId: __t.string(),
  ownerIdentity: __t.identity(),
});
export type ParticipantOwner = __Infer<typeof ParticipantOwner>;

export const Presence = __t.object("Presence", {
  participantId: __t.string(),
  zoneId: __t.string(),
  isDemoPersona: __t.bool(),
});
export type Presence = __Infer<typeof Presence>;

export const PublicProfile = __t.object("PublicProfile", {
  participantId: __t.string(),
  displayName: __t.string(),
  headline: __t.string(),
  interests: __t.string(),
});
export type PublicProfile = __Infer<typeof PublicProfile>;

export const PublicProfiles = __t.object("PublicProfiles", {});
export type PublicProfiles = __Infer<typeof PublicProfiles>;

export const UserProfile = __t.object("UserProfile", {
  identity: __t.identity(),
  displayName: __t.string(),
  headline: __t.string(),
  interests: __t.string(),
  showOnMap: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type UserProfile = __Infer<typeof UserProfile>;

