"""Photon Pup's screens for the native display app → native/photon/display/photon_assets.c (RGB565, like ogvegas).

Each scene is one full 320×240 screen; the animated scenes add small "tiles" (just the puppy's area at other bob
offsets) that are redrawn with st7789_set_window + st7789_blit, so animation costs ~50 KB per frame, not 150 KB.

  python3 native/make_assets.py        (run from freewili/, uses the same pixel UI as the laptop mirror)
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from photon_fw.display import H, W, compose  # noqa: E402

OUT = ROOT / "native" / "photon" / "display"
G, Y, B, R, GR = (60, 190, 110), (248, 205, 79), (70, 150, 255), (235, 80, 80), (170, 170, 185)
HOME = [(G, "hi"), (Y, "coffee"), (B, "nap"), (GR, "quit")]

# name: (sprite, title, subtitle, hints, heart, tile bob offsets)
SCENES = {
    "idle": ("idle", "ready to meet?", "catch matches to make your pup happy", HOME, True, (3, 0, -3)),
    "lonely": ("searching", "looking for people...", "your pup misses people", HOME, False, ()),
    "match": ("match", "match found!", "press GREEN for a double yes!", [(G, "YES!"), (R, "skip")], True, ()),
    "yes": ("double_yes", "double yes!", "+1 social", [], True, (3, -3)),
    "miss": ("waiting", "too slow...", "next one will come!", [], False, ()),
    "coffee": ("found", "coffee break!", "+1 energy", [], True, ()),
    "nap": ("offline", "nap time... zzz", "press BLUE to nap, energy refills", [(B, "nap")], False, ()),
}
TILE = (60, 24, 200, 128)  # x, y, w, h: covers the sprite at any bob offset


def rgb565(im) -> list[int]:
    return [((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3) for r, g, b in im.convert("RGB").getdata()]


def c_array(name: str, px: list[int]) -> str:
    rows = [", ".join(f"0x{v:04X}" for v in px[i : i + 16]) for i in range(0, len(px), 16)]
    return f"static const uint16_t {name}[{len(px)}] = {{\n" + ",\n".join(rows) + "\n};\n"


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    parts = ["/* Generated by native/make_assets.py from the Photon pixel UI. Do not edit. */",
             '#include "photon_assets.h"', ""]
    table, total = [], 0
    for i, (name, (sp, title, sub, hints, heart, bobs)) in enumerate(SCENES.items()):
        full = compose(sp, title, sub, hints, 0, heart)
        parts.append(c_array(f"full_{name}", rgb565(full)))
        total += W * H
        tiles = []
        for j, bob in enumerate(bobs):
            x, y, w, h = TILE
            tile = compose(sp, title, sub, hints, bob, heart).crop((x, y, x + w, y + h))
            parts.append(c_array(f"tile_{name}_{j}", rgb565(tile)))
            tiles.append(f"tile_{name}_{j}")
            total += w * h
        tl = ", ".join(tiles) if tiles else "0"
        parts.append(f"static const uint16_t *const tiles_{name}[] = {{{tl}}};\n")
        table.append(f"    {{full_{name}, tiles_{name}, {len(tiles)}}},  /* {i}: {name} */")
    parts.append("const photon_scene_t photon_scenes[PHOTON_SCENE_COUNT] = {\n" + "\n".join(table) + "\n};")
    (OUT / "photon_assets.c").write_text("\n".join(parts) + "\n")
    print(f"{len(SCENES)} scenes, {total * 2 / 1024:.0f} KB of pixels → {OUT / 'photon_assets.c'}")


if __name__ == "__main__":
    main()
