"""Build the single-file Agentverse Hosted artifact from the tested source modules."""
from pathlib import Path


def build():
    root = Path(__file__).parent
    transport = (root / 'asi_networking_agent.py').read_text()
    entry = (root / 'asi_hosted_agent.py').read_text()
    for line in ['from asi_networking_agent import make_protocol\n', 'from asi_hosted_backend import NativeChatBackend\n']:
        entry = entry.replace(line, '')
    source = '# Generated by agents/build_asi_hosted.py. Edit the tested source modules.\n' + transport + '\n' + (root / 'asi_hosted_backend.py').read_text() + '\n' + entry
    path = root / 'hosted/agent.py'
    path.parent.mkdir(exist_ok=True)
    path.write_text(source, encoding='utf-8')
    return path


if __name__ == '__main__':
    print(build())
